# This workflow will install Python dependencies and upload a version in the PyPI test environment
name: CD - Test PyPI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Sets up python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Install dependencies
      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
          python3 setup.py install

      # Upload to TestPyPI
      - name: Build and Upload to TestPyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine check dist/*
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
          TWINE_REPOSITORY: testpypi